meta_product_name: "GuessWhat"
meta_title: "GuessWhat - The best blind test app ever"
meta_description: "Challenge your friends ! Choose a music style, launch a party, guess the songs and earn points !"
meta_image: "cover.png" # should exist in `app/assets/images/`
